version: '3.7'
services:
  mosquitto:
    image: nazt/mosquitto:1.4.9
    volumes:
      - $PWD/configs/mosquitto.conf:/mosquitto/mosquitto.conf
    ports:
      - "9001:9001"
      - "1883:1883"
    restart: always
